# -*- coding: utf-8 -*-
"""CPL_AOT_PointBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1topI0pLE6z8qImlhyfg5c9GFKgi3UnVR
"""

# mount google Drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# clone github repo
# clone to fast local SSD
# %cd /content
!rm -rf aot-cpl-point-bot
!git clone https://github.com/mduboef/aot-cpl-point-bot.git
# %cd /content/aot-cpl-point-bot

# sanity check
import torch, pickle
print("CUDA:", torch.cuda.is_available())
for p in ["data/trainingData/trainPreferences.pkl", "data/testingData/testPreferences.pkl"]:
    with open(p, "rb") as f:
        print(p, "→", len(pickle.load(f)), "pairs")

# check if reference policy is stored in GH models directory
print("REF_POLICY cached:", __import__("os").path.isfile("models/REF_POLICY/policy.pt"))
# TODO if no ref policy train a BC ref policy
if not __import__("os").path.isfile("models/REF_POLICY/policy.pt"):
  print("NOT IMPLEMENTED: NEED TO TRAIN REF_POLICY")

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir models

# train all six methods at once, save each to Drive when it finishes
import subprocess, os, re, shutil, datetime, time

methods   = ["bc", "cpl", "cpl_biased", "cpl_paot", "cpl_uaot", "cpl_uaot_ref"]
stamp     = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
driveRoot = f"/content/drive/MyDrive/UMass/CPL (Independent Study Fall 2026)/Distributional CPL/runs/{stamp}"
logDir    = os.path.join(driveRoot, "logs")
os.makedirs(logDir, exist_ok=True)

# limit threads per process so 6 procs don't oversubscribe the CPU cores
nCores  = os.cpu_count() or 8
perProc = max(1, nCores // len(methods))
env     = dict(os.environ, OMP_NUM_THREADS=str(perProc), MKL_NUM_THREADS=str(perProc))

before = set(os.listdir("models"))

# launch all six concurrently; each streams its console output to its own log file in Drive
procs, logs = {}, {}
for m in methods:
    lf = open(os.path.join(logDir, f"{m}.log"), "w")
    procs[m] = subprocess.Popen(
        ["python3", "-u", "train.py", "--method", m],
        stdout=lf, stderr=subprocess.STDOUT, env=env)
    logs[m] = lf
    print(f"launched {m:14s} pid {procs[m].pid}  (OMP_NUM_THREADS={perProc})", flush=True)

# poll; as each finishes, copy its exact new run dir to Drive immediately
saved, done = set(), set()
while len(done) < len(methods):
    time.sleep(15)
    for m, p in procs.items():
        if m in done or p.poll() is None:
            continue
        logs[m].flush(); logs[m].close()
        status = "OK" if p.returncode == 0 else f"FAILED(rc={p.returncode})"
        # match ONLY this method's dir: ^TAG_<digits>$  (so 'cpl' won't grab 'cpl_biased' etc.)
        pat = re.compile(rf"^{m.upper()}_\d+$")
        new = [d for d in os.listdir("models")
               if d not in before and d not in saved and pat.match(d)]
        for d in new:
            shutil.copytree(os.path.join("models", d),
                            os.path.join(driveRoot, "models", d), dirs_exist_ok=True)
            saved.add(d)
            print(f"[{m}] {status} → saved models/{d} to Drive", flush=True)
        if not new:
            print(f"[{m}] {status} but no new run dir found — check logs/{m}.log", flush=True)
        done.add(m)

print("\nALL DONE →", driveRoot)

# print final eval metrics for the 6 just-trained models
import os, re, json

methods = ["bc", "cpl", "cpl_biased", "cpl_paot", "cpl_uaot", "cpl_uaot_ref"]
split   = "test"  # held-out set; switch to "train" to see fit on training pairs

# for each method pick the run dir created this session (highest N for the exact tag)
def latestRunDir(method):
      tag = method.upper()
      pat = re.compile(rf"^{tag}_(\d+)$")
      matches = [(int(pat.match(d).group(1)), d)
              for d in os.listdir("models") if pat.match(d)]
      return os.path.join("models", max(matches)[1]) if matches else None

header = ["Method", "Orig-Pair Acc", "pAOT Loss", "pAOT Viol Rate", "uAOT Loss", "uAOT Viol Rate", "Avg Reward"]
rows = []
for m in methods:
      runDir = latestRunDir(m)
      if runDir is None:
              rows.append([m, "no run dir", "", "", "", "", ""])
              continue
      with open(os.path.join(runDir, "eval_stats.json")) as f:
              stats = json.load(f)
      acc   = stats["preferenceAccuracy"][split]["overall"]
      paot  = stats["paotLoss"][split]
      uaot  = stats["uaotLoss"][split]

      rollouts = stats.get("rollouts", [])
      if rollouts:
          avg_reward = sum(r.get("reward", 0) for r in rollouts) / len(rollouts)
          reward_str = f"{avg_reward:.2f}"
      else:
          reward_str = "N/A"

      rows.append([
              m,
              f"{acc:.1%}",
              f"{paot['paotLoss']:.4f}",
              f"{paot['violationFreq']:.1%}",
              f"{uaot['uaotLoss']:.4f}",
              f"{uaot['violationFreq']:.1%}",
              reward_str
      ])

# print an aligned table
widths = [max(len(str(r[i])) for r in ([header] + rows)) for i in range(len(header))]
def fmtRow(r):
      return "  ".join(str(c).ljust(widths[i]) for i, c in enumerate(r))
print(f"evaluation metrics on the {split} set\n")
print(fmtRow(header))
print("  ".join("-" * w for w in widths))
for r in rows:
      print(fmtRow(r))