bc_warmup_steps: 20000
cpl_paot_steps: 30000
batch_size: 256
paot_batch_size: 32
lr: 0.0001
alpha: 0.1
gamma: 1.0
contrastive_bias: 0.2    # bias regularization (λ): downweights "score" for negative segments in margin calculation

log_interval: 500        # how often we print training progress
eval_interval: 100       # how often we get eval metrics + log likelihood for TensorBoard 
rollout_interval: 500    # how often we rollout & get avg reward for TensorBoard
n_eval_rollouts: 25      # rollouts per rollout_interval